### ISSUE TITLE
Error to manage when trying to create a competition without any existing gym 

### ISSUE THREAD

**Issue by scorreia** [dmossakowski/skala3ma#17]
Start the application for the very time (no data created)
Login and create a new competition  (without having first created a gym).

then, we get this error: 
Traceback (most recent call last):
  File "/Users/scorreia/devel/git/skala3ma/.venv/lib/python3.11/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/scorreia/devel/git/skala3ma/.venv/lib/python3.11/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/scorreia/devel/git/skala3ma/.venv/lib/python3.11/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/scorreia/devel/git/skala3ma/.venv/lib/python3.11/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/scorreia/devel/git/skala3ma/.venv/lib/python3.11/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/scorreia/devel/git/skala3ma/.venv/lib/python3.11/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/scorreia/devel/git/skala3ma/.venv/lib/python3.11/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/scorreia/devel/git/skala3ma/.venv/lib/python3.11/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/scorreia/devel/git/skala3ma/.venv/lib/python3.11/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/scorreia/devel/git/skala3ma/.venv/lib/python3.11/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/scorreia/devel/git/skala3ma/competitionsApp.py", line 163, in decorated_function
    return fn(*args, **kwargs)
  File "/Users/scorreia/devel/git/skala3ma/competitionsApp.py", line 693, in new_competition_post
    competitionId = competitionsEngine.addCompetition(None, name, date, routesid, max_participants)
  File "/Users/scorreia/devel/git/skala3ma/competitionsEngine.py", line 149, in addCompetition
    competition = {"id": compId, "name": name, "date": date, "gym": gym['name'],"gym_id":gym['id'],

**Comment by dmossakowski** [comment]
A gym must first be created before creating a competition
